[package]
name = "csv_app"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
actix-web = "4"
csv_lib = { path = "../csv_lib" }