[package]
name = "csv_lib"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
actix-multipart = "0.6"
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
csv = "1"